import '@/src/styles/index.css'
import { theme } from '@/src/styles/theme'
import type { AppProps } from 'next/app'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import { ThemeProvider } from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Challenge Eyecue 2024</title>
        <meta name='description' content='Generated by Nicolas Viotti' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ThemeProvider theme={theme}>
        <main className={`${inter.className}`}>
          <Component {...pageProps} />
        </main>
      </ThemeProvider>
    </>
  )
}
